version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017 # only accessible from localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
